version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: emlakos-postgres-dev
    environment:
      POSTGRES_DB: emlakos_turkiye
      POSTGRES_USER: emlakos_user
      POSTGRES_PASSWORD: emlakos_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - emlakos-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: emlakos-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - emlakos-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Frontend (Next.js) - Development
  frontend:
    build:
      context: ./frontend/web-app
      dockerfile: Dockerfile.dev
    container_name: emlakos-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - DATABASE_URL=postgresql://emlakos_user:emlakos_password_2024@postgres:5432/emlakos_turkiye
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./frontend/web-app:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - emlakos-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  emlakos-network:
    driver: bridge
