version: '3.8'

services:
  # PostgreSQL + PostGIS - En güvenli ve hızlı veritabanı
  postgres:
    image: postgis/postgis:15-3.3
    container_name: emlakos-postgres
    environment:
      POSTGRES_DB: emlakos_turkiye
      POSTGRES_USER: emlakos_admin
      POSTGRES_PASSWORD: EmlakOS2024!SecureDB
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      # SSL Configuration (disabled for local development)
      POSTGRES_SSL_MODE: disable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./backups:/backups
    networks:
      - emlakos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emlakos_admin -d emlakos_turkiye -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c log_connections=on
      -c log_disconnections=on
      -c log_statement=all
      -c log_min_duration_statement=1000
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

  # Redis - Hızlı cache ve session yönetimi
  redis:
    image: redis:7-alpine
    container_name: emlakos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - emlakos-network
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin - Veritabanı yönetimi
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: emlakos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@emlakos.com
      PGADMIN_DEFAULT_PASSWORD: EmlakOS2024!Admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - emlakos-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  emlakos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
